# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: connections_development
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql2
  encoding: utf8
  database: connections_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: connections_production
  pool: 5
  timeout: 5000
